# Generated by Django 2.1 on 2018-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'todo'), ('INPROGRESS', 'inprogress'), ('DONE', 'done')], default='TODO', max_length=12)),
            ],
        ),
    ]
